// Generated by assets/helix/build_title_motion.py; original palette 0..223.
#define HELIX_TITLE_SPRITE_REGION_COUNT 2
#define HELIX_TITLE_SPRITE_FRAME_COUNT 32
#define HELIX_TITLE_SPRITE_FRAME_TICKS 8
#define HELIX_TITLE_SPRITE_FRAME_BYTES 2304
#define HELIX_TITLE_SPRITE_REGIONS {{13, 7, 4, 5}, {14, 13, 4, 4}}
