"""Check deterministic public-only identities and their immutable art binding.

No private files, accepted packages, providers or saves are read. The checked-in
header is generated solely from the namespace below and explicitly reused art.
These fixtures cannot be used with development/accepted saves. This checker does
not build or admit a gameplay package. --write explicitly regenerates the header.
"""
from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
import re
import zlib

ROOT = Path(__file__).resolve().parents[1]
OVERLAY = ROOT / "rom-source" / "overlay"
HEADER = OVERLAY / "include" / "constants" / "helix_public_fixture.h"
NAMESPACE = "pokemon-helix/public-source-fixture/v1"


def derive(label: str, size: int) -> bytes:
    data = b""
    counter = 0
    while len(data) < size:
        data += hashlib.sha256(f"{NAMESPACE}/{label}/{counter}".encode()).digest()
        counter += 1
    return data[:size]


def byte_array(data: bytes) -> str:
    return "{" + ", ".join(f"0x{value:02x}" for value in data) + "}"


def matrix(label: str, rows: int, columns: int, bound: int | None = None) -> str:
    values = [derive(f"{label}/{index}", columns) for index in range(rows)]
    if bound is not None:
        values = [bytes(value % bound for value in row) for row in values]
    return "{" + ", ".join(byte_array(row) for row in values) + "}"


def render() -> str:
    # This is an original authored image conversion, reused without regenerating
    # or attributing its appearance to these unrelated synthetic genomes.
    art_source = (OVERLAY / "src/data/aurora_individual_art.h").read_text()
    body = re.search(r"sAuroraIndividualArt\[[^]]+\]\s*=\s*\{(.*?)\};", art_source, re.S)
    if body is None:
        raise ValueError("Missing original-art byte array")
    payload = bytes(int(value, 16) for value in re.findall(r"0x([0-9a-fA-F]{2})\b", body[1]))
    if len(payload) != 2080:
        raise ValueError("Unexpected original-art payload geometry")
    art_hash = hashlib.sha256(payload).digest()
    art_crc = zlib.crc32(payload)
    identity = derive("legacy-individual/id", 12)
    genome = derive("legacy-individual/genome", 16)
    art_files = [OVERLAY / "src/data/aurora_individual_art.h"]
    for family in ("lumifin", "lumifin_child", "lumifin_child_edited"):
        for asset in ("front.png", "back.png", "icon.png", "normal.pal"):
            art_files.append(OVERLAY / "graphics/pokemon" / family / asset)
    binding = {
        "namespace": NAMESPACE,
        "individual_id": identity.hex(),
        "genome": genome.hex(),
        "art_payload_sha256": art_hash.hex(),
        "art_files": {path.relative_to(OVERLAY).as_posix(): hashlib.sha256(path.read_bytes()).hexdigest()
                      for path in art_files},
    }
    binding_bytes = json.dumps(binding, sort_keys=True, separators=(",", ":")).encode()
    values = {
        "HELIX_PUBLIC_INDIVIDUAL_ID": byte_array(identity),
        "HELIX_PUBLIC_INDIVIDUAL_GENOME": byte_array(genome),
        "HELIX_PUBLIC_INDIVIDUAL_ART_HASH": byte_array(art_hash),
        "HELIX_PUBLIC_INDIVIDUAL_ART_CRC": f"0x{art_crc:08x}",
        "HELIX_PUBLIC_INDIVIDUAL_PERSONALITY": f"0x{int.from_bytes(derive('legacy-individual/personality', 4), 'little'):08x}",
        "HELIX_PUBLIC_CHILD_PERSONALITY": f"0x{int.from_bytes(derive('legacy-child/personality', 4), 'little'):08x}",
        "HELIX_PUBLIC_ROSTER_MANIFEST_CRC": f"0x{zlib.crc32(binding_bytes):08x}",
        "HELIX_PUBLIC_IDENTITY_ART_BINDING": byte_array(hashlib.sha256(binding_bytes).digest()),
        "HELIX_PUBLIC_NOTES_PACKAGE_HASH": byte_array(derive("notes/package-placeholder", 32)),
        "HELIX_PUBLIC_CORAL_PACKAGE_HASH": byte_array(derive("blocked-coral/package-placeholder", 32)),
        "HELIX_PUBLIC_DEX_GENOMES": matrix("dex/genome", 3, 96),
        "HELIX_PUBLIC_DEX_CHANGES": matrix("dex/change-mask", 3, 24),
        "HELIX_PUBLIC_DEX_IDS": matrix("dex/id", 3, 32),
        "HELIX_PUBLIC_DEX_PROFILE_HASHES": matrix("dex/profile-placeholder", 3, 32),
        "HELIX_PUBLIC_DEX_TRAIT_SCORES": matrix("dex/trait-fixture", 3, 16, 101),
        "HELIX_PUBLIC_RIVAL_OT": f"0x{int.from_bytes(derive('rival/ot', 4), 'little'):08x}",
        "HELIX_PUBLIC_ADVENTURE_FIRST_PERSONALITY": f"0x{int.from_bytes(derive('disabled-adventure/first', 4), 'little'):08x}",
        "HELIX_PUBLIC_ADVENTURE_SECOND_PERSONALITY": f"0x{int.from_bytes(derive('disabled-adventure/second', 4), 'little'):08x}",
    }
    prefix = '''#ifndef GUARD_CONSTANTS_HELIX_PUBLIC_FIXTURE_H
#define GUARD_CONSTANTS_HELIX_PUBLIC_FIXTURE_H

// Generated by scripts/check-public-native-fixtures.py --write.
// Namespace: pokemon-helix/public-source-fixture/v1
// Synthetic source fixtures only. NEVER use accepted/development saves.
// These package/profile placeholders do not admit or reproduce any package.
// Reused artwork does not represent these artificial genomes or trait scores.
#define HELIX_PUBLIC_SOURCE_FIXTURE 1
'''
    return prefix + "\n".join(f"#define {key} {value}" for key, value in values.items()) + "\n\n#endif\n"


def check_disabled_packages() -> None:
    for name, flag in (("helix_genesis_content.h", "HELIX_GENESIS"),
                       ("aurora_adventure_content.h", "AURORA_ADVENTURE")):
        content = (OVERLAY / "include/constants" / name).read_text()
        if not re.search(rf"^#define {flag}_ENABLED 0$", content, re.M):
            raise ValueError("Public source export must keep accepted packages disabled")
    genesis = (OVERLAY / "src/helix_genesis.c").read_text()
    if "#define HELIX_CROSS_ADMISSION_RELEASED 0" not in genesis:
        raise ValueError("CORAL admission gate is missing")


def check_source_bindings() -> None:
    bindings = {
        "src/aurora_individual.c": {"sIndividualId": "HELIX_PUBLIC_INDIVIDUAL_ID", "sIndividualGenome": "HELIX_PUBLIC_INDIVIDUAL_GENOME", "sIndividualArtHash": "HELIX_PUBLIC_INDIVIDUAL_ART_HASH"},
        "src/helix_lab.c": {"sNotesPackageHash": "HELIX_PUBLIC_NOTES_PACKAGE_HASH", "sCoralPackageHash": "HELIX_PUBLIC_CORAL_PACKAGE_HASH"},
        "src/helix_pokedex.c": {"gHelixPokedexPackageHash": "HELIX_PUBLIC_NOTES_PACKAGE_HASH", "sCoralPackageHash": "HELIX_PUBLIC_CORAL_PACKAGE_HASH", "gHelixPokedexGenome": "HELIX_PUBLIC_DEX_GENOMES", "gHelixPokedexChanges": "HELIX_PUBLIC_DEX_CHANGES", "sIndividualIds": "HELIX_PUBLIC_DEX_IDS", "sProfileHashes": "HELIX_PUBLIC_DEX_PROFILE_HASHES", "sTraitScores": "HELIX_PUBLIC_DEX_TRAIT_SCORES"},
    }
    for name, symbols in bindings.items():
        source = (OVERLAY / name).read_text()
        for symbol, macro in symbols.items():
            if not re.search(rf"const u8 {symbol}(?:\[[^]]+\])+\s*=\s*{macro};", source):
                raise ValueError("Public array binding changed: " + name + ":" + symbol)
    constants = {
        "include/constants/aurora_individual.h": {"AURORA_INDIVIDUAL_PERSONALITY": "HELIX_PUBLIC_INDIVIDUAL_PERSONALITY"},
        "include/constants/aurora_roster.h": {"AURORA_ROSTER_MANIFEST_CRC": "HELIX_PUBLIC_ROSTER_MANIFEST_CRC", "AURORA_CHILD_PERSONALITY": "HELIX_PUBLIC_CHILD_PERSONALITY"},
        "include/constants/aurora_adventure_content.h": {"AURORA_ADVENTURE_FIRST_PERSONALITY": "HELIX_PUBLIC_ADVENTURE_FIRST_PERSONALITY", "AURORA_ADVENTURE_SECOND_PERSONALITY": "HELIX_PUBLIC_ADVENTURE_SECOND_PERSONALITY"},
        "src/aurora_individual.c": {"INDIVIDUAL_ART_CRC": "HELIX_PUBLIC_INDIVIDUAL_ART_CRC"},
        "src/helix_genesis.c": {"HELIX_RIVAL_OT": "HELIX_PUBLIC_RIVAL_OT"},
    }
    for name, symbols in constants.items():
        source = (OVERLAY / name).read_text()
        for symbol, macro in symbols.items():
            if f"#define {symbol} {macro}\n" not in source:
                raise ValueError("Public constant binding changed: " + name + ":" + symbol)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write", action="store_true", help="Regenerate only the public fixture header")
    args = parser.parse_args()
    check_disabled_packages()
    check_source_bindings()
    expected = render()
    if args.write:
        HEADER.write_text(expected)
    if HEADER.read_text() != expected:
        raise ValueError("Public identity/art binding changed; inspect before regenerating")
    print("Public fixture identities, art binding and disabled package gates verified.")


if __name__ == "__main__":
    main()
