#ifndef GUARD_CONSTANTS_AI_BRIDGE_H
#define GUARD_CONSTANTS_AI_BRIDGE_H

#ifndef AURORA_LANGUAGE_PT_BR
#define AURORA_LANGUAGE_PT_BR 0
#endif

#define AI_BRIDGE_MAGIC 0x31414247
#define AI_BRIDGE_VERSION 1
#define AI_BRIDGE_RESPONSE_CAPACITY 240
#define AI_BRIDGE_TIMEOUT_FRAMES 600

#define AI_BRIDGE_IDLE 0
#define AI_BRIDGE_REQUEST 1
#define AI_BRIDGE_RESPONSE 2
#define AI_BRIDGE_CANCELLED 3
#define AI_BRIDGE_ERROR 4

#define AI_BRIDGE_RESULT_NONE 0
#define AI_BRIDGE_RESULT_RECEIVED 1
#define AI_BRIDGE_RESULT_TIMEOUT 2
#define AI_BRIDGE_RESULT_CANCELLED 3
#define AI_BRIDGE_RESULT_INVALID 4
#define AI_BRIDGE_RESULT_OFFLINE 5

#define AI_NPC_IVO 1
#define AI_NPC_RECEPTION 2
#define AI_NPC_GENETICIST 3
#define AI_NPC_NURSERY 4
#define SIGNAL_MOTIVATION_NONE 0
#define SIGNAL_MOTIVATION_CURIOSITY 1
#define SIGNAL_MOTIVATION_VILLAGE 2
#define SIGNAL_QUEST_NOT_STARTED 0
#define SIGNAL_QUEST_ACCEPTED 1
#define SIGNAL_QUEST_CLUE_FOUND 2
#define SIGNAL_QUEST_REPORTED 3

#endif
