#ifndef GUARD_CONSTANTS_AURORA_INDIVIDUAL_H
#define GUARD_CONSTANTS_AURORA_INDIVIDUAL_H

#include "constants/helix_public_fixture.h"

#define AURORA_INDIVIDUAL_MAGIC 0x31495541
#define AURORA_INDIVIDUAL_VERSION 1
#define AURORA_INDIVIDUAL_PAYLOAD_SIZE 2080
#define AURORA_INDIVIDUAL_SAVE_SIZE 76
#define AURORA_INDIVIDUAL_OPERATION_HATCH 1
#define AURORA_INDIVIDUAL_OPERATION_VIEW 2
#define AURORA_INDIVIDUAL_RESULT_CACHED 6
#define AURORA_INDIVIDUAL_RESULT_PARTY_FULL 7
#define AURORA_INDIVIDUAL_EMPTY 0
#define AURORA_INDIVIDUAL_PRESENT 1
#define AURORA_INDIVIDUAL_UNSUPPORTED 2

// Record flags: v1 specimen-only saves remain readable. Once issued, a
// released/traded companion is never manufactured again from the art registry.
#define AURORA_INDIVIDUAL_FLAG_ISSUED 2
#define AURORA_INDIVIDUAL_ISSUED (AURORA_INDIVIDUAL_PRESENT | AURORA_INDIVIDUAL_FLAG_ISSUED)
#define AURORA_INDIVIDUAL_PERSONALITY HELIX_PUBLIC_INDIVIDUAL_PERSONALITY

#define AURORA_INDIVIDUAL_PARTY_ABSENT 0
#define AURORA_INDIVIDUAL_PARTY 1
#define AURORA_INDIVIDUAL_BOXED 2
#define AURORA_INDIVIDUAL_MISSING 3
#define AURORA_INDIVIDUAL_PARTY_UNSUPPORTED 4

#endif
