#ifndef GUARD_CONSTANTS_AURORA_ADVENTURE_CONTENT_H
#define GUARD_CONSTANTS_AURORA_ADVENTURE_CONTENT_H

#include "constants/helix_public_fixture.h"

// Disabled legacy build. Preparation installs an immutable package's generated
// header for its separate ROM, then restores this file. Never edit legacy art.
#define AURORA_ADVENTURE_ENABLED 0
#define AURORA_ADVENTURE_VARIANT 0
#define AURORA_ADVENTURE_ID_BYTES {0}
#define AURORA_ADVENTURE_PACKAGE_BYTES {0}
#define AURORA_ADVENTURE_FIRST_ID_BYTES {0}
#define AURORA_ADVENTURE_SECOND_ID_BYTES {0}
#define AURORA_ADVENTURE_FIRST_PERSONALITY HELIX_PUBLIC_ADVENTURE_FIRST_PERSONALITY
#define AURORA_ADVENTURE_SECOND_PERSONALITY HELIX_PUBLIC_ADVENTURE_SECOND_PERSONALITY
#define AURORA_ADVENTURE_FIRST_NAME "AURORA ONE"
#define AURORA_ADVENTURE_SECOND_NAME "AURORA TWO"

#define AURORA_COMBAT_ENABLED 0

#endif
