#ifndef GUARD_CONSTANTS_HELIX_SETTINGS_H
#define GUARD_CONSTANTS_HELIX_SETTINGS_H

#define HELIX_SETTINGS_MAGIC 0x31534C48
#define HELIX_SETTINGS_VERSION 1
#define HELIX_SETTINGS_TIMEOUT 300
#define HELIX_SETTINGS_REFRESH 120
#define HELIX_SETTINGS_UNKNOWN_MINUTE 65535

#define HELIX_SETTINGS_IDLE 0
#define HELIX_SETTINGS_REQUEST 1
#define HELIX_SETTINGS_RESPONSE 2
#define HELIX_SETTINGS_ERROR 3

#define HELIX_SETTINGS_QUERY 1
#define HELIX_SETTINGS_SET_INTERNET 2
#define HELIX_SETTINGS_SET_MICROPHONE 3
#define HELIX_SETTINGS_OPEN_ACCOUNT 4
#define HELIX_SETTINGS_OPEN_MICROPHONE 5
#define HELIX_SETTINGS_TIME_AUTO 6
#define HELIX_SETTINGS_OPEN_TIMEZONE 7
#define HELIX_SETTINGS_SET_LANGUAGE 8
#define HELIX_SETTINGS_OPEN_ADVANCED 9
#define HELIX_SETTINGS_SET_TIMEZONE 10
#define HELIX_SETTINGS_SET_VOICE 11
#define HELIX_SETTINGS_CHECK_KEYS 12
#define HELIX_SETTINGS_IMPORT_COPIED_KEY 13
#define HELIX_SETTINGS_REMOVE_KEY 14
#define HELIX_SETTINGS_TIMEZONE_COUNT 599
#define HELIX_SETTINGS_CUSTOM_TIMEZONE 65535

#define HELIX_SETTINGS_OK 0
#define HELIX_SETTINGS_UNAVAILABLE 1
#define HELIX_SETTINGS_PANEL_OPENED 2
#define HELIX_SETTINGS_CONFLICT 3
#define HELIX_SETTINGS_INVALID 4

#define HELIX_SETTINGS_CAP_DIALOGUE 1
#define HELIX_SETTINGS_CAP_VOICE 2
#define HELIX_SETTINGS_CAP_ACCOUNT 4

#endif
